USE GAMIFIED
GO
CREATE TABLE Char_Loc
(
	Char_ID INT NOT NULL,
	Loc_ID INT NOT NULL,
	FOREIGN KEY(Char_ID) REFERENCES Char_Stats(Char_ID),
	FOREIGN KEY(Loc_ID) REFERENCES Location(Loc_ID)
)
GO