USE GAMIFIED
GO

CREATE TABLE Monster_Loc
(
	Mon_ID INT NOT NULL,
	Loc_ID INT NOT NULL,
	FOREIGN KEY(Mon_ID) REFERENCES Monster_Stats(Mon_ID),
	FOREIGN KEY(Loc_ID) REFERENCES Location (Loc_ID)
)